Repository atlp-rwanda/phantom-fe-elite, pull requests merged in 2022-05, with the labels that each got.

#17 #36 Feature: register driver & operator
  package-lock.json
  package.json
  postcss.config.js
  public/trackroute.jpg
  src/App.js
  src/App.test.js
  src/Routes/RegisterPage.js
  src/assets/images/trackroute.jpg
  src/assets/styles/styles.css
  src/component/FormSubscribe.js
  src/component/NavBar.js
  src/component/__test__/LandingPage.test.js
  src/component/__test__/RegisterPage.test.js
  src/component/footer-and-nav-template/FooterBlock.js
  src/component/footer-and-nav-template/NavBar.js
  src/component/starter-files-draft/NumCounter.js
  src/component/starter-files-draft/counter.css
  src/index.html
  src/index.js
  src/main.css
  src/redux/actions/counterActions.js
  src/redux/reducers/counterReducer.js
  tailwind.config.js
  webpack.config.js
Labels: help wanted

#18 Ft reset ps 31
  package-lock.json
  package.json
  postcss.config.js
  src/App.js
  src/App.test.js
  src/Routes/InputForm.js
  src/Routes/LandingPage.js
  src/Routes/RegisterPage.js
  src/Routes/Reset.js
  src/Routes/confirmation-password.js
  src/Routes/loginPage.js
  src/Routes/reset.css
  src/assets/FINAL-LOGO.jpg
  src/assets/FINAL-LOGO.png
  src/assets/imgs/jali.jpg
  src/assets/imgs/kbs.jpg
  src/assets/imgs/landing-image.jpg
  src/assets/imgs/logo.jpg
  src/assets/imgs/loyal.jpg
  src/assets/imgs/phantom-letter-o.jpg
  src/assets/imgs/rftc.jpg
  src/assets/imgs/rura.jpg
  src/assets/imgs/trackroute.jpg
  src/component/NavBar.js
  src/component/__test__/LandingPage.test.js
  src/component/__test__/LoginPage.test.js
  src/component/__test__/Register.test.js
  src/component/__test__/RegisterPage.test.js
  src/component/__test__/Reset.test.js
  src/component/footer-and-nav-template/FooterBlock.js
  src/component/footer-and-nav-template/NavBar.js
  src/component/footer-and-nav-template/style.css
  src/component/landingPage/LandingPage.js
  src/component/login.js
  src/component/navigation/NavBar.js
  src/component/starter-files-draft/NumCounter.js
  src/index.html
  src/main.css
  src/postcss.config.js
  src/redux/Routes/AboutPage.js
  src/redux/Routes/Home.js
  src/template.html
  tailwind.config.js
  webpack.config.js
Labels: work-in-progress

#24 #10 Feature: Update profile for Driver
  data/db.json
  package-lock.json
  package.json
  postcss.config.js
  src/App.js
  src/Routes/AboutPage.js
  src/Routes/Home.js
  src/Routes/InputForm.js
  src/Routes/LandingPage.js
  src/Routes/RegisterPage.js
  src/assets/images/logo.png
  src/component/__test__/LandingPage.test.js
  src/component/__test__/RegisterPage.test.js
  src/component/__test__/UpdateDriver.test.js
  src/component/__test__/UpdateOperator.test.js
  src/component/dash/Footer.js
  src/component/dash/Header.js
  src/component/dash/MobileHeader.js
  src/component/dash/SideBar.js
  src/component/dash/SideBarDriver.js
  src/component/footer-and-nav-template/NavBar.js
  src/component/layout/Admin.js
  src/component/layout/DriverDashboard.js
  src/component/layout/Layout.js
  src/component/starter-files-draft/counter.css
  src/index.html
  src/redux/actions/counterActions.js
  src/template.html
  src/views/driver/UpdateDriver.js
  src/views/operator/Bus.js
  src/views/operator/UpdateOperator.js
  tailwind.config.js
Labels: Ready for review

#20 #33 Feature: CRUD operations for bus
  data/db.json
  package-lock.json
  src/App.js
  src/Routes/Router.js
  src/component/EditBusModal.js
  src/component/NewBusModal.js
  src/component/__test__/Bus.test.js
  src/component/__test__/LoginPage.test.js
  src/component/__test__/RegisterPage.test.js
  src/component/__test__/Reset.test.js
  src/component/dashboard-layout/Footer.js
  src/component/dashboard-layout/Header.js
  src/component/dashboard-layout/MobileHeader.js
  src/component/dashboard-layout/SideBar.js
  src/component/dashboard-layout/SideBarDriver.js
  src/component/dashboard-layout/SideBarOperator.js
  src/component/layout/Admin.js
  src/component/layout/DriverDashboard.js
  src/component/layout/Layout.js
  src/views/AboutPage.js
  src/views/Home.js
  src/views/InputForm.js
  src/views/LandingPage.js
  src/views/RegisterPage.js
  src/views/Reset.js
  src/views/confirmation-password.js
  src/views/login.js
  src/views/operator/Bus.js
  src/views/reset.css
Labels: Ready for review

#30 #30Feature:logout
  src/component/__test__/Dropdown.test.js
  src/component/dashboard-layout/Dropdown.js
  src/component/dashboard-layout/Header.js
Labels: Ready for review

#32 #12:Fix:Fix react workflows
  .github/workflows/Build.yml
  .github/workflows/Coverage.yml
  .github/workflows/react.yml
  README.md
Labels: Ready for review

#29 #34 Feature: routes CRUD operations for operator
  data/db.json
  package-lock.json
  package.json
  src/Routes/Router.js
  src/__mocks__/axios.js
  src/assets/AdminOperatorIntegration.testi.js
  src/component/NewRouteModal.js
  src/component/UpdateRouteModal.js
  src/component/__test__/RouteLines.test.js
  src/component/new_route/ListContent.js
  src/component/new_route/ListHeader.js
  src/component/new_route/TableRow.js
  src/views/operator/RouteLines.js
Labels: Ready for review
